language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
before-script:
  - npm install coveralls --save-dev
script:
  - CI=true npm test -- --coverage && coveralls < coverage/lcov.info
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
