version: "3"

services:
  client:
    build: ./client
    command: yarn run start
    ports: 
      - "3000:3000"
    volumes:
      - ./client:/client
    links:
      - api
  api:
    build: ./api
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: sh -c
      "
        python manage.py makemigrations &&
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "
    environment:
      - DB_HOST=db
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASS=secret
    depends_on:
      - db
  db:
    image: postgres:10-alpine
