# Generated by Django 2.1.12 on 2019-09-15 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=60)),
                ('title', models.CharField(default='title', max_length=60)),
                ('meta', models.CharField(default='meta', max_length=100)),
                ('desc', models.CharField(default='desc', max_length=100)),
                ('detail', models.CharField(default='detail', max_length=300)),
                ('img', models.CharField(default='img', max_length=100)),
                ('src', models.CharField(default='src', max_length=100)),
            ],
        ),
    ]
